# Generated by Django 5.2.1 on 2025-05-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_product_category_product_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaruselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='karusel_products/')),
                ('is_main', models.BooleanField(default=False)),
            ],
        ),
    ]
