# Generated by Django 5.2.1 on 2025-06-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='фио')),
                ('number_phone', models.CharField(max_length=12, verbose_name='телефон')),
                ('pochta', models.EmailField(max_length=254, verbose_name='почта')),
                ('cat', models.CharField(max_length=900, verbose_name='сообщение')),
            ],
        ),
    ]
