# Generated by Django 5.2.1 on 2025-06-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='skidka_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='цена со скидкой'),
        ),
    ]
