# Generated by Django 5.2.1 on 2025-06-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_skidka_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='karuselimage',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Сылка'),
        ),
    ]
