# Generated by Django 5.2.1 on 2025-07-29 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_telegramuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='emailrecipient',
            options={'verbose_name': 'Gmail Рассылка', 'verbose_name_plural': 'Gmail Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='karuselimage',
            options={'verbose_name': 'Фотка Карусели', 'verbose_name_plural': 'Фотки Карусели'},
        ),
        migrations.AlterModelOptions(
            name='letter',
            options={'verbose_name': 'Письмо Менеджеру', 'verbose_name_plural': 'Письма Менеджерам'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Элементы заказа', 'verbose_name_plural': 'Элементы заказов'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение продукта', 'verbose_name_plural': 'Изображении продуктов'},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Телеграм пользовател', 'verbose_name_plural': 'Телеграм пользователи'},
        ),
    ]
